# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ["reaction_app.py"],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        "PySide6",
        "shiboken6",
        "PyQt6",
        "streamlit",
        "notebook",
        "jupyterlab",
        "IPython",
        "pytest",
        "sphinx",
        "tkinter",
        "spyder",
        "panel",
        "bokeh",
        "polars",
        "pyarrow",
        "botocore",
        "aiobotocore",
        "s3fs",
        "dask",
        "distributed",
        "numba",
        "llvmlite",
        "plotly",
        "astropy",
        "statsmodels",
        "skimage",
        "sklearn",
        "mpi4py",
        "matplotlib.tests",
        "pandas.tests",
    ],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="水体反应管检测系统",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name="水体反应管检测系统",
)
